version: "2017-09-20"
pipeline:
- id: build-spilo-cdp
  env: &ENV
    BASE_IMAGE: registry.opensource.zalan.do/library/ubuntu-18.04
    IMAGE: registry-write.opensource.zalan.do/acid/spilo
    PGVERSION: 14
  type: script
  commands:
  - desc: Build spilo docker image
    cmd: |
      cd postgres-appliance
      docker build --build-arg PGVERSION=$PGVERSION --build-arg BASE_IMAGE=$BASE_IMAGE -t spilo .
      docker images
  - desc: Test spilo docker image
    cmd: |
      sudo apt-get update
      sudo apt-get install -y python3-pip
      sudo pip3 install docker-compose==1.17.1
      bash postgres-appliance/tests/test_spilo.sh
  - desc: Tag and push spilo-cdp docker image
    cmd: |
      # push docker images only for commits to the master branch
      if [ "x${CDP_SOURCE_BRANCH}" == "x" ] && [ "x${CDP_TARGET_BRANCH}" == "xfeature/postgresql-14" ]; then
          cd postgres-appliance
          PATRONIVERSION=$(sed -n 's/^ENV PATRONIVERSION=\([1-9][0-9]*\.[0-9]*\).*$/\1/p' Dockerfile)
          IMAGE="$IMAGE-cdp-$PGVERSION:$PATRONIVERSION-p$CDP_TARGET_BRANCH_COUNTER"
          docker build --build-arg PGVERSION=$PGVERSION --build-arg BASE_IMAGE=$BASE_IMAGE -t $IMAGE .
          docker images
          docker push $IMAGE
      fi
